package vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Angelo
 */
public class VistaTragamonedas extends JFrame {

    /**
     * Creates new form VistaTragamonedas
     */
    public VistaTragamonedas() {
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/ico.png"));
        setIconImage(icono.getImage());
        setTitle("Tragamonedas :: $$");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        casino = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        ruleta = new javax.swing.JLabel();
        btnC1 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        cbmodo = new javax.swing.JComboBox<>();
        btnregreso = new javax.swing.JButton();
        btngirar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casino.jpeg"))); // NOI18N
        panel.add(casino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 325, 116));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/1.jpeg"))); // NOI18N
        panel.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 90, 80));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/1.jpeg"))); // NOI18N
        panel.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/1.jpeg"))); // NOI18N
        panel.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 90, 80));

        ruleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrete.jpeg"))); // NOI18N
        panel.add(ruleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 390, 200));

        btnC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.jpg"))); // NOI18N
        panel.add(btnC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 50));

        btnC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.jpg"))); // NOI18N
        panel.add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 50, 50));

        btnC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.jpg"))); // NOI18N
        panel.add(btnC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 60, 50));

        cbmodo.setBackground(new java.awt.Color(255, 0, 153));
        cbmodo.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        cbmodo.setMaximumRowCount(4);
        cbmodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EASY✅", "NORMAL", "VERY HARD" }));
        cbmodo.setToolTipText("");
        cbmodo.setAlignmentX(1.0F);
        cbmodo.setAlignmentY(1.0F);
        panel.add(cbmodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        btnregreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regreso.png"))); // NOI18N
        panel.add(btnregreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 60, 50));

        btngirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Start.png"))); // NOI18N
        panel.add(btngirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ColumnaO.png"))); // NOI18N
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ColumnaO.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel C1;
    public static javax.swing.JLabel C2;
    public static javax.swing.JLabel C3;
    public javax.swing.JButton btnC1;
    public javax.swing.JButton btnC2;
    public javax.swing.JButton btnC3;
    public javax.swing.JButton btngirar;
    public javax.swing.JButton btnregreso;
    private javax.swing.JLabel casino;
    public javax.swing.JComboBox<String> cbmodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel ruleta;
    // End of variables declaration//GEN-END:variables
}
