package vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Angelo
 */
public class VistaUnete extends JFrame {

    /**
     * Creates new form Unete
     */
    public VistaUnete() {
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/ico.png"));
        setIconImage(icono.getImage());
        setTitle("Tragamonedas :: $$");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUnete = new javax.swing.JPanel();
        btnbackU = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spiedad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cbsexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        campoRFC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRUnete = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUnete.setBackground(new java.awt.Color(0, 0, 0));
        panelUnete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbackU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regreso.png"))); // NOI18N
        panelUnete.add(btnbackU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 70, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡INGRESE SUS DATOS SI DESEA SER PARTE DE NUESTRO GRAN EQUIPO!");
        panelUnete.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        panelUnete.add(campoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE:");
        panelUnete.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APELLIDO:");
        panelUnete.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));
        panelUnete.add(campoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 150, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CORREO:");
        panelUnete.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));
        panelUnete.add(campoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 130, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EDAD:");
        panelUnete.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));
        panelUnete.add(spiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 50, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SEXO:");
        panelUnete.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        cbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMBRE", "MUJER", "PREFIERONODECIRLO" }));
        panelUnete.add(cbsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RFC:");
        panelUnete.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        campoRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRFCActionPerformed(evt);
            }
        });
        panelUnete.add(campoRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moneda.gif"))); // NOI18N
        panelUnete.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ColumnaO.png"))); // NOI18N
        panelUnete.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ColumnaO.png"))); // NOI18N
        panelUnete.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRUnete.setText("REGISTRAR");
        panelUnete.add(btnRUnete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/welcome.png"))); // NOI18N
        panelUnete.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 370, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelUnete, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUnete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRFCActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRUnete;
    public javax.swing.JButton btnbackU;
    public javax.swing.JTextField campoA;
    public javax.swing.JTextField campoN;
    public javax.swing.JTextField campoR;
    public javax.swing.JTextField campoRFC;
    public javax.swing.JComboBox<String> cbsexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelUnete;
    public javax.swing.JSpinner spiedad;
    // End of variables declaration//GEN-END:variables
}
