package vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Angelo
 */
public class VistaInicio extends JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public VistaInicio() {
        ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/ico.png"));
        setIconImage(icono.getImage());
        setTitle("Tragamonedas :: $$");
        setSize(400,400);
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        panel1 = new javax.swing.JPanel();
        botonplay = new javax.swing.JButton();
        logojuego = new javax.swing.JLabel();
        btnregistro = new javax.swing.JButton();
        moneda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnunete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuSalir = new javax.swing.JMenu();
        itemsalir = new javax.swing.JMenuItem();
        MenuAcercade = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonplay.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        botonplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PLAY.jpg"))); // NOI18N
        botonplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonplayActionPerformed(evt);
            }
        });
        panel1.add(botonplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, 80));
        botonplay.getAccessibleContext().setAccessibleDescription("");

        logojuego.setBackground(new java.awt.Color(0, 0, 0));
        logojuego.setForeground(new java.awt.Color(0, 0, 0));
        logojuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logojuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpeg"))); // NOI18N
        panel1.add(logojuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 350, 160));

        btnregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hotel.jpeg"))); // NOI18N
        btnregistro.setToolTipText("");
        panel1.add(btnregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 200, 60));

        moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moneda.gif"))); // NOI18N
        panel1.add(moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 120, 460, 310));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/moneda.gif"))); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 840, -1));

        btnunete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unete.jpeg"))); // NOI18N
        btnunete.setPreferredSize(new java.awt.Dimension(200, 70));
        btnunete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuneteActionPerformed(evt);
            }
        });
        panel1.add(btnunete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 348, 200, 70));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        MenuSalir.setText("Opciones🛠️");

        itemsalir.setText("Salir❌");
        MenuSalir.add(itemsalir);

        jMenuBar1.add(MenuSalir);

        MenuAcercade.setText("🚩Acerca de: ");

        jMenuItem1.setForeground(new java.awt.Color(0, 102, 255));
        jMenuItem1.setText("Authors: Angelo Emmanuel & Luis Enrique😎 ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuAcercade.add(jMenuItem1);

        jMenuBar1.add(MenuAcercade);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonplayActionPerformed
    
    }//GEN-LAST:event_botonplayActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnuneteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuneteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnuneteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuAcercade;
    public javax.swing.JMenu MenuSalir;
    public javax.swing.JButton botonplay;
    public javax.swing.JButton btnregistro;
    public javax.swing.JButton btnunete;
    public javax.swing.JMenuItem itemsalir;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel logojuego;
    private javax.swing.JLabel moneda;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
